export const CREATE_GROUP = 'CREATE GROUP'
export const ACTIVATE_GROUP = 'ACTIVATE GROUP'
export const EDIT_GROUP = 'EDIT GROUP'
export const REMOVE_GROUP = 'REMOVE GROUP'
export const ADD_THERAPIST_TO_GROUP = 'ADD THERAPIST TO GROUP'
export const ADD_PATIENT_TO_GROUP = 'ADD PATIENT TO GROUP'
export const REMOVE_THERAPIST_FROM_GROUP = 'REMOVE THERAPIST FROM GROUP'
export const REMOVE_PATIENT_FROM_GROUP = 'REMOVE PATIENT FROM GROUP'
export const DELIVER_BIO = 'DELIVER BIO'
export const SET_THREE_MONTH_DATE = 'SET THREE MONTH DATE'
export const CHANGE_CLINIC_BIOFLOW_ACCESS = 'CHANGE CLINIC BIOFLOW ACCESS'
export const INVITE_THERAPIST = 'INVITE THERAPIST'
export const REMOVE_THERAPIST = 'REMOVE THERAPIST'
export const REMOVE_THERAPIST_INVITE = 'REMOVE THERAPIST INVITE'
export const CREATE_STUDY = 'CREATE STUDY'
export const EDIT_STUDY = 'EDIT STUDY'
export const REMOVE_STUDY = 'REMOVE STUDY'

export default {
  CREATE_GROUP,
  ACTIVATE_GROUP,
  EDIT_GROUP,
  REMOVE_GROUP,
  ADD_THERAPIST_TO_GROUP,
  ADD_PATIENT_TO_GROUP,
  REMOVE_THERAPIST_FROM_GROUP,
  REMOVE_PATIENT_FROM_GROUP,
  DELIVER_BIO,
  SET_THREE_MONTH_DATE,
  CHANGE_CLINIC_BIOFLOW_ACCESS,
  INVITE_THERAPIST,
  REMOVE_THERAPIST,
  REMOVE_THERAPIST_INVITE,
  CREATE_STUDY,
  EDIT_STUDY,
  REMOVE_STUDY
}
