export const DRAFT_STATUS = 'DRAFT'
export const FINISHED_STATUS = 'FINISHED'
export const ONGOING_STATUS = 'ONGOING'
export const FUTURE_STATUS = 'FUTURE'

export default [DRAFT_STATUS, FINISHED_STATUS, ONGOING_STATUS, FUTURE_STATUS]
